apiVersion: apps/v1
kind: Deployment
metadata:
  name: iweblens-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iweblens
  template:
    metadata:
      labels:
        app: iweblens
    spec:
      containers:
      - name: iweblens-container
        image: avinashharesh/iweblens-image:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "0.5"
